### ISSUE TITLE
Cannot find module 'ethereumjs-wallet/hdkey' by using truffle-config.js

### ISSUE THREAD

**Issue by micli** [OpenZeppelin/openzeppelin-solidity#1129]
## 🎉 Description

I want to use truffle-config.js to deploy my smart contract to testnet like ropsten, kovan. Unfortunately, I always got "Cannot find module 'ethereumjs-wallet/hdkey'" error when I run "trufffle.cmd migrate --reset --network ropsten".

- [x ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?
The Master branch.
- What network are you deploying to? Ganache? Ropsten?
Ropsten and kovan.
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!
truffle.

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here.

## 🔢 Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

```
C:\ethereum\JarvisPlusCrowdsale>truffle.cmd migrate --reset --network development
Error: Cannot find module 'ethereumjs-wallet/hdkey'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\ethereum\JarvisPlusCrowdsale\node_modules\truffle-hdwallet-provider\index.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\ethereum\JarvisPlusCrowdsale\truffle.js:16:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.Config.load (C:\Users\mic_l\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-config\index.js:254:1)
    at Function.Config.detect (C:\Users\mic_l\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-config\index.js:243:1)
    at Object.run (C:\Users\mic_l\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\commands\migrate.js:35:1)
    at Command.run (C:\Users\mic_l\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\command.js:101:1)
    at Object.<anonymous> (C:\Users\mic_l\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\cli.js:16:1)
    at __webpack_require__ (C:\Users\mic_l\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap f3b0126a12cf2ee05457:19:1)
    at C:\Users\mic_l\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap f3b0126a12cf2ee05457:65:1
    at Object.<anonymous> (C:\Users\mic_l\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:71:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

## 👍 Other Information
I am using Windows 10 with nodejs 10.7.0.
I can confirm that I have already installed "ethereumjs-wallet" and hdkey.js has been in the sub folder of ethereumjs-wallet in node_modules.

**Comment by roschler** [comment]
@micli You will find the solution here:

https://github.com/trufflesuite/truffle-hdwallet-provider/issues/54

**Comment by micli** [comment]
It has been resolved after I installed truffle-hdwallet-provider 0.6.0.
`
npm uninstall ethereumjs-wallet
npm uninstall truffle-hdwallet-provider
npm install ethereumjs-wallet@0.6.0 --save
npm install --save truffle-hdwallet-provider@0.0.3
`

**Comment by micli** [comment]
One more question.
I only have 3 kovan ethers. I just want to publish my contract to kovan testnet. But It seems I don't have  enough fund to do this:
$ truffle migrate --reset --network kovan
Using network 'kovan'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 672197500000000000 and got: 0.

Below is my kovan net configuration:
var MNEMONIC = "XXX XXX XXX XXX";

const HDWalletProvider = require('truffle-hdwallet-provider');

const providerWithMnemonic = (mnemonic, rpcEndpoint) =>
  new HDWalletProvider(mnemonic, rpcEndpoint);

const infuraProvider = network => providerWithMnemonic(
  process.env.MNEMONIC || '',
  `https://${network}.infura.io/${process.env.INFURA_API_KEY}`
);

module.exports = {
  networks: {
    kovan: {
      provider: infuraProvider('kovan'),
      //gasPrice: 1000000000,
      network_id: 42, // eslint-disable-line camelcase
    },
......

I don't know how to set my wallet and how to make contract deployment successfully.
Thanks!

**Comment by Levino** [comment]
`0.0.6` not `0.6.0`
