### ISSUE TITLE
Issue publishing ERC721 Contract using Open Zeppelin.

### ISSUE THREAD

**Issue by alexacostarua** [OpenZeppelin/openzeppelin-solidity#1388]
sudo truffle migrate --network rinkeby
Using network 'rinkeby'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: exceeds block gas limit
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessa
ge.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

When i tried to deploy my contract to the rinkeby net, from a truffle setup.  Dont know how to fix block gas limit issue.

**Comment by alexacostarua** [comment]
I also added all the contracts from the 1.12 version of openzepp and tried to migrate in truffle, it compiled.

**Comment by alexacostarua** [comment]
If i include contracts and files in the truffle setup will that contribute to the block limit for the rinkeby or not?

**Comment by alexacostarua** [comment]
I got it to deploy but when I try to call a function with the correct contract n abi code. It doesn’t have any functions available at all thru myetherwallet. Do ERC721 functions exist there. If so how do u interact with them through MEW?
Thanks.

On Oct 6, 2018, at 11:10 PM, Nicolás Venturo <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you share the code you're trying to deploy? There are many possible reasons for you to get this error.
