### ISSUE TITLE
contract creation without any data provided

### ISSUE THREAD

**Issue by dmitry537** [OpenZeppelin/openzeppelin-solidity#943]
Contract uses ERC721Token can not be deployed by truffle.  

```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: contract creation without any data provided
    at Object.InvalidResponse (C:\Users\Kh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
    at C:\Users\Kh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
    at C:\Users\Kh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-core\~\truffle-migrate\index.js:225:1
    at C:\Users\Kh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\Kh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\Kh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\Kh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\Kh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\Kh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Example:
```
pragma solidity ^0.4.23;
import 'zeppelin-solidity/contracts/token/ERC721/ERC721Token.sol';
contract Token is ERC721Token {
}
```
Geth
Version: 1.8.7-stable
Git Commit: 66432f3821badf24d526f2d9205f36c0543219de
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: windows

truffle 
Version
Solidity v0.4.23 (solc-js)

How can this be solved?

**Comment by dougiebuckets** [comment]
@dmitry537 I might be missing something, but it doesn't appear you've initialized your contract correctly and constructor arguments in ERC721Token.sol are going unsatisfied.

I'm new to OpenZeppelin and had a similar problem the other day. It inspired me to draft up the following. Hope it's helpful.

[How To Manually Test Your OpenZeppelin Secure Smart Contracts](https://blog.upstate.agency/how-to-manually-test-your-openzeppelin-secure-smart-contracts-df4f751fd56c)

**Comment by elopio** [comment]
@dougiebuckets thanks for the answer (and the post). I'm closing it; but @dmitry537, please let us know if you have further questions.

**Comment by robertmagier** [comment]
I have my contract defined as follows and I still get exactly same error:
```
pragma solidity ^0.4.21;

import "openzeppelin-solidity/contracts/token/ERC20/DetailedERC20.sol";

contract TestToken is DetailedERC20{

  uint public number = 256;

  constructor () public DetailedERC20('test','test',18)
  {
    number = 1;
  }
}

```

I get this error:
```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: contract creation without any data provided
    at Object.InvalidResponse (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
    at C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
    at C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-migrate\index.js:225:1
    at C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

Any idea ?

**Comment by DJXia** [comment]
I think this problem is not related to 721. It seems that there are some conflict under the build of the contract with different network. Try to delete all the contract json files in the build folder and re-compile and migrate?

**Comment by robertmagier** [comment]
Hi. Thanks for reply. I tried to remove all json files and recompile and migrate again. Didn't help. 
You are right. It is not related to 721. It ERC20 token.

**Comment by robertmagier** [comment]
I did some investigation. Unfortunately this error message has nothing to do with the problem. 
It seems truffle throws some error messages when it is not possible to deploy contract to blockchain. In this case it is not possible to deploy because DetailedERC20 contract is an abstract contract. You have to also import StandardToken contract. 

Correct code would be:
```

pragma solidity ^0.4.21;

import "openzeppelin-solidity/contracts/token/ERC20/DetailedERC20.sol";
import "openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol";

contract TestToken is StandardToken,DetailedERC20{

  uint public number = 256;

  constructor () DetailedERC20('test','test',18) public
  {
    number = 1;
  }
}
```

**Comment by sprect8** [comment]
robertmagier, you da real mvp

Thanks, I was struggling with the same problem and you hit the nail on the head

**Comment by SantanaRuben** [comment]
Thanks to @DJXia I solved my problem. It seems I renamed the contract because I changed the first letter to uppercase, that maked my tests impossible to pass because the artifacts on the builder folder were different when I compiled.
